# Site settings
baseURL = "https://lianapshevorska.com"
languageCode = "en-US"
title = "Liana Pshevorska"
theme = "split"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2018 Liana Pshevorska"

[params]

  # Metadata for search engines and social sharing
  author = "Liana Pshevorska"
  description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
  shareImage = "images/social.jpg"
  twitterHandle = ""

  # Favicon
  # favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Nav
  #
  [[params.nav]]
    [params.nav.page1]
      heading = "Bio"
      url = "/"
    [params.nav.page2]
      heading = "Research"
      url = "/research/"
    [params.nav.page3]
      heading = "Teaching"
      url = "/teaching/"
    [params.nav.page4]
      heading = "Contact"
      url = "/contact/"
    [params.nav.page5]
      heading = "CV"
      url = "/pdf/pshevorska-cv.pdf"
      newtab = true

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
